--- #YAML:1.0
name:                Number-Phone-Normalize
version:             0.20
abstract:            Normalizes format of Phone Numbers.
license:             perl
author:              
    - Claus Faerber <CFAERBER@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
